workspace:
  base: /go
  path: src

pipeline:
  build:
    image: golang:1.8
    commands:
      - echo "Build Phase"
  test:
    image: golang:1.8
    commands:
      - echo "Test Phase"
      
services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=postgres
  mysql:
    image: mysql:5.6.27
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
